/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Lander: typeof import('./components/Lander.vue')['default']
    RelativeCosts: typeof import('./components/proposal/RelativeCosts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineProposal: typeof import('./components/proposal/TimelineProposal.vue')['default']
    WrittenProposal: typeof import('./components/proposal/WrittenProposal.vue')['default']
  }
}
